# Generated by Django 5.1.1 on 2024-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Todo Title')),
                ('desription', models.TextField(max_length=300, verbose_name='Description')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Todo Create Date')),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
    ]
