# Generated by Django 5.1.1 on 2024-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50, unique=True, verbose_name='Department Name')),
                ('dep_description', models.TextField(max_length=300, verbose_name='Department Description')),
            ],
        ),
    ]
