# Generated by Django 5.1.1 on 2024-10-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.IntegerField(max_length=10, unique=True, verbose_name='Contact Number')),
            ],
        ),
    ]
