# Generated by Django 5.1.1 on 2024-10-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
