# Generated by Django 5.1.1 on 2024-10-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='Phone_Number',
        ),
    ]
